### ISSUE TITLE
oculus go: movement-control differs when using http or https

### ISSUE THREAD

**Issue by dr-br** [aframevr/aframe#4437]
**Description:**  
Oculus Go: When touching the controller touchpad, I expect translational movement. This works, as long I use unencrypted (http) connection to the server. When using encrypted (https) connection, the translational movement no longer works. Instead a rotation is triggered.

I'm not sure, if this bug is related to aframe or aframe-extras, because the bug starts at aframe v1.0.1, while behavior is unaffected by aframe-extras version.

- A-Frame Version: master (aee952b1), BUG starting at v1.0.1
- Platform / Device: Oculus Go
- Reproducible Code Snippet or URL:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script src="./aframe/dist/aframe-master.min.js"></script>
    <script src="./aframe-extras/dist/aframe-extras.js"></script>
  </head>
  <body>
    <a-scene>
      <a-box position="-1 0.5 -3" rotation="0 45 0" color="#4CC3D9"></a-box>
      <a-entity oculus-go-controls></a-entity>
      <a-entity movement-controls="fly: true; speed: 1">
        <a-entity camera position="0 1.6 0"></a-entity>
      </a-entity>
    </a-scene>
  </body>
</html>
```

---
**Helping documents:**
* Server: [h2o](https://github.com/h2o/h2o) or `apt install h2o`, other servers behave the same
* Server config `/etc/h2o/h2o.conf`:  
```
hosts:
  "mydomain.com":
    listen:
      port: 443
      ssl:
        certificate-file: /path/to/localhost.crt
        key-file: /path/to/localhost.key
    paths:
      "/":
        file.dir: /path/to/content/
  "mydomain.com:80":
    listen:
      port: 80
    paths:
      "/":
        file.dir: /path/to/content/

```
* Self-signed SSL-Cert:  
```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout localhost.key -out localhost.crt
```
