### ISSUE TITLE
Disable text selection of all canvases because it looks weird in Chrome

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#584]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Tuesday Oct 27, 2015 at 00:48 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/327_

----

![text-selection-canvas](https://cloud.githubusercontent.com/assets/203725/10746552/55ad0d6a-7c09-11e5-8fc6-981b780b8f06.gif)

1. Load http://localhost:9001/examples/panoexplorer/
2. Double click on the page a couple times
3. Notice the blue highlight, especially visible with the three block images
4. Select the entire text of the page (using __`Command` + `A`__)
5. Notice the blue highlight again

How to fix?

This is a start:

```css
.vr-canvas {
  -webkit-user-select: none;
  -moz-user-select: none;
  user-select: none;
}

::selection {
  background: transparent;
}

::moz-selection {
  background: transparent;
}
```

But it doesn't completely solve the problem. And you don't want to disable the text-selection color for the entire page; there could be a sidebar, text/legend at the top or bottom of the site.

I think you need to actually do like disable text selection on all the canvases like so:

```js
canvas.addEventListener('selectionstart', function () {
  // stop propagation *and* prevent default!
  return false;
});
```

There's probably some better solution. Investigate!
