### ISSUE TITLE
aframe mixin stylesheets (naming tbd)

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#909]
```css
// stylesheet.mixins
#cube {
  geometry {
    primitive: 'box';
  }
}

#red {
  material {
    color: 'red';
  }
}
```

```html
<a-scene>
  <a-assets>
    <a-stylesheet src="stylesheet.mixins></a-stylesheet>
    <a-stylesheet>
      #green { material { color: 'green'; } }
      #sphere { geometry { primitive: 'sphere'; radius: 5 } }
    </a-stylesheet>
  </a-assets>

  <a-entity mixin="red cube"></a-entity>
  <a-entity mixin="green sphere"></a-entity>
  <a-entity mixin="red sphere"></a-entity>
</a-scene>
```
